/**
 * 《社畜日記》文案集中管理
 * 所有 UI 中文一律放這裡。語氣原則:陪伴、不評價、溫暖但不過度雞湯。
 */
export const copy = {
  app: {
    name: '社畜日記',
  },
  login: {
    slogan: '在不滿意的日子裡，找到屬於你的快樂',
    lineLogin: '使用LINE帳號登錄',
    googleLogin: '使用Google帳號登入',
    divider: '或使用電子郵件登入',
    emailPlaceholder: '電子郵件',
    passwordPlaceholder: '密碼',
    forgotPassword: '忘記密碼？',
    loginButton: '登入',
    noAccount: '還沒有帳號？',
    registerLink: '立即註冊',
    terms: '登入即代表同意',
    termsLink: '服務條款',
    and: '與',
    privacyLink: '隱私政策',
  },
  register: {
    heading: '放鬆一下，開始記錄吧',
    subheading: '給自己一點關懷，輕鬆踏入日記的世界',
    lineRegister: '使用LINE帳號註冊',
    googleRegister: '使用Google帳號註冊',
    divider: '或使用電子郵件註冊',
    nicknamePlaceholder: '幫自己取個暱稱',
    emailPlaceholder: '電子郵件',
    passwordPlaceholder: '設定密碼（至少 8 個字元）',
    confirmPasswordPlaceholder: '再輸入一次密碼',
    passwordMismatch: '兩次密碼不一樣，再確認看看',
    registerButton: '開始打卡！',
    hasAccount: '已有帳號？',
    loginLink: '返回登入',
    terms: '註冊即代表同意',
    termsLink: '服務條款',
    and: '與',
    privacyLink: '隱私政策',
  },
  home: {
    greeting: 'Dear, LuLu',
    subtitle: '今天也辛苦了，記得照顧自己 🌿',
    quickRecord: '記一下今天',
    todayPrompt: '要不要記一格,看看今天踩到哪個職場陷阱?',
    myDiary: '日記本',
    coinTitle: '今日金幣',
    coinUnit: '枚',
    boardCardTitle: '社畜大富翁',
    boardViewMap: '查看完整地圖 →',
    boardForward: '前進大富翁 →',
    emotionDetect: '偵測到你今天似乎有點',
    emotionDetectAction: '點一下，讓易經陪你靜下來想一想',
    weeklySummaryTitle: '本週前進總覽',
    weeklySummaryEmotion: '情緒分布',
    weeklySummaryTrigger: '本週主要觸發原因',
    weeklySummaryAI: 'AI 小提醒',
    nav: {
      home: '首頁',
      board: '職涯大富翁',
      diary: '日記',
      analytics: '分析庫銀行',
      profile: '我的',
    },
  },
  dateStrip: {
    backToToday: '回到今天',
    backfillPrompt: '想幫這天補一筆嗎?',
    futurePlaceholder: '這一天還沒發生,先好好過今天吧',
  },
  energyJar: {
    todayCoins: '今日金幣',
    totalCoins: (n: number | string) => `累積 ${n} 枚`,
    moodTallyTitle: '今日心情',
  },
  diary: {
    stepMood: '今天感覺如何?',
    stepEvent: '發生什麼事?',
    stepNote: '想補一句話嗎?(可以不寫)',
    done: '記好了,今天也往前走了一格',
    // 日記本首頁
    yearSuffix: '年',
    monthSuffix: '月',
    weekDays: ['日', '一', '二', '三', '四', '五', '六'],
    weekDaysFull: ['週日', '週一', '週二', '週三', '週四', '週五', '週六'],
    entriesCount: (n: number) => `共 ${n} 筆日記`,
    emptyTitle: '這天沒有紀錄',
    searchPlaceholder: '搜尋日記內容或標籤…',
    // 日記編輯頁
    editorTitle: '今天，想記下什麼呢？',
    editorPlaceholder: '寫下今天發生的事，或只是一句話也可以⋯',
    editorMoodPrompt: '今天的心情比較像...',
    editorTagPrompt: '這件事跟...',
    editorAddTag: '＋ 新增標籤',
    editorSave: '儲存日記',
    editorBackToDiary: '回到日記本',
    editorSaveLater: '等等再寫',
    moodShortLabels: { happy: '開心', calm: '平靜', ordinary: '平凡', achievement: '有成就感', depressed: '憂鬱', hurt: '委屈', angry: '憤怒' } as Record<string, string>,
  },
  diaryDetail: {
    coinNote: (n: number | string) => `這筆記錄 +${n} 金幣`,
    menuDelete: '收回這筆',
    deleteConfirm: '記錄送出後無法修改。要收回這筆嗎?它會從地圖和分析中移除',
    deleteYes: '收回',
    deleteNo: '留著',
  },
  board: {
    title: '職涯大富翁',
    rollDice: '擲骰子',
    energyNotEnough: '能量還在恢復中,先休息一下吧',
  },
  analytics: {
    title: '分析庫銀行',
    subtitle: '把每一次紀錄，存成看懂自己的資產',
    bankCardDeposited: '已存入',
    bankCardUnit: '篇日記',
    bankCardStreak: (n: number | string) => `持續紀錄 ${n} 天`,
    enduranceTitle: '忍受地圖',
    enduranceSubtitle: '哪些事真的讓你受不了',
    resonancePrefix: '',
    statsNote: (n: number | string) => `根據你最近 ${n} 篇日記統計`,
    detailLink: '查看更詳細分析 →',
    radarTitle: '壓力雷達圖',
    keywordsTitle: '高頻關鍵字',
    aiTitle: 'AI 職涯探索報告',
    aiViewFull: '查看完整報告 →',
    unlockPlus: '解鎖 Plus，看見完整忍受地圖',
    unlockPro: '解鎖 Pro，查看 AI 職涯報告',
    guideTitle: '當你準備好了',
    guideSoon: '即將推出，敬請期待',
  },
  profile: {
    title: '我的',
    editProfile: '編輯個人資料',
    diariesCount: '篇日記',
    streakCount: '天持續紀錄',
    currentPlan: '目前方案：Free',
    unlockPlus: '解鎖 Plus 看見你的壓力雷達圖',
    upgradePlan: '升級方案',
    sectionPrivacy: '隱私與安全',
    privacyLock: '密碼鎖 / Face ID',
    nicknameSettings: '匿名暱稱設定',
    quietNotify: '低調通知模式',
    quietNotifyDesc: '通知不顯示日記內容',
    sectionGeneral: '一般設定',
    notifySettings: '通知設定',
    darkMode: '深色模式',
    language: '語言',
    langValue: '繁體中文',
    sectionAbout: '關於社畜日記',
    systemUpdate: '系統更新紀錄',
    currentVersion: '目前版本 v1.2.0',
    feedback: '意見回饋',
    aboutUs: '關於我們',
    loginAccount: '登入帳號設定',
    logout: '登出',
    logoutConfirm: '要登出嗎?你的記錄都會好好保存',
    logoutYes: '登出',
    logoutNo: '再待一下',
  },
} as const;
